---
- name: 'Common configuration'
  hosts: 'all'
  gather_facts: True
  sudo: True

  roles:
    - { role: geerlingguy.security, tags: security }
    - { role: nickjj.fail2ban, sudo: true, tags: fail2ban }
    - { role: DavidWittman.redis, tags: redis }
    - { role: nickhammond.logrotate, tags: logrotate }
    - { role: geerlingguy.java, tags: java }
    - { role: geerlingguy.elasticsearch, tags: elasticsearch }
    - { role: franklinkim.openssl, tags: openssl }
    - { role: jdauphant.nginx, tags: nginx }
    - { role: franklinkim.nodejs, tags: nodejs }
    - { role: franklinkim.timezone, tags: timezone }
    - { role: franklinkim.users, tags: users }
    - { role: franklinkim.users-oh-my-zsh, tags: ohmyzsh }
    - { role: franklinkim.ufw, tags: ufw }
    - { role: zzet.rbenv, tags: rbenv }
    - { role: alekseyp.papertrail, tags: papertrail }

  tasks:
    - name: fix locales
      shell: >
        locale-gen en_US.UTF-8 && dpkg-reconfigure -fnoninteractive locales && update-locale LC_ALL="en_US.UTF-8" LANG="en_US.UTF-8" LANGUAGE="en_US" && touch ~/.locale_ok creates=~/.locale_ok

    - name: update apt cache
      apt: update_cache=yes

    - name: upgrade system
      apt: upgrade=safe

    - name: install required packages
      apt: pkg={{ item }}
      with_items:
        - build-essential
        - git-core
        - libxml2-dev
        - python-psycopg2
        - libpq-dev
        - imagemagick
        - zlib1g-dev
        - libssl-dev
        - libyaml-dev
        - libxml2-dev
        - bison
        - libreadline6
        - libreadline6-dev
        - python-passlib
      tags:
        - apt-packages

    - name: ensure bitbucket.org is a known host
      lineinfile:
        dest: /root/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}"
        regexp: "^bitbucket\\.org"

    - name: Source rbenv in ~/.zshrc
      lineinfile: dest=/home/nerdmaster/.zshrc line='export PATH="$HOME/.rbenv/bin:$PATH"' state=present insertafter=EOF create=yes
      tags:
        - rbenv-export

    - name: Add rbenv init to ~/.zshrc to enable shims and autocomplete
      lineinfile: dest=/home/nerdmaster/.zshrc line='eval "$(rbenv init -)"' state=present insertafter=EOF create=yes
      tags:
        - rbenv-init

    - name: Move unicorn init.d config script
      template: src=templates/unicorn_eunerd.j2 dest=/etc/init.d/unicorn mode="a+rx"
      tags:
        - initd_unicorn

    - name: Add unicorn startup on update.rc
      shell: >
        update-rc.d -f unicorn defaults
      tags:
        - initd_unicorn

    - name: Move sidekiq init.d config script
      template: src=templates/sidekiq_eunerd.j2 dest=/etc/init/sidekiq.conf mode="a+rx"
      tags:
        - initd_sidekiq

    # - name: Add sidekiq on /etc/init/startup on update.rc
    #   shell: >
    #     update-rc.d -f sidekiq defaults
    #   tags:
    #     - initd_sidekiq

    - name: Generate htpasswd file for nginx
      htpasswd: path=/etc/htpasswd/encontreumnerd name=eunerd password=eunerd owner=root group=www-data mode=0640
      tags:
        - htpasswd

    - name: create the file to be used for swap
      command: fallocate -l 1G /mnt/1GB.swap
      tags:
        - swap

    - name: format the file for swap
      command: mkswap /mnt/1GB.swap
      tags:
        - swap

    - name: change swap file permissions
      file: path=/mnt/1GB.swap owner=root group=root mode=0600
      tags:
        - swap

    - name: add the file to the system as a swap file
      command: swapon /mnt/1GB.swap
      tags:
        - swap

    - name: write swap entry in fstab
      mount: name=none src=/mnt/1GB.swap fstype=swap opts=sw passno=0 dump=0 state=present
      tags:
        - swap
