---
- name: 'Common configuration'
  hosts: 'all'
  gather_facts: True
  sudo: True

  roles:
    - { role: geerlingguy.security, tags: security }
    - { role: nickjj.fail2ban, sudo: true, tags: fail2ban }
    - { role: DavidWittman.redis, tags: redis }
    - { role: nickhammond.logrotate, tags: logrotate }
    - { role: geerlingguy.java, tags: java }
    - { role: geerlingguy.elasticsearch, tags: elasticsearch }
    - { role: franklinkim.openssl, tags: openssl }
    - { role: jdauphant.nginx, tags: nginx }
    - { role: franklinkim.nodejs, tags: nodejs }
    - { role: franklinkim.timezone, tags: timezone }
    - { role: franklinkim.users, tags: users }
    - { role: franklinkim.users-oh-my-zsh, tags: ohmyzsh }
    - { role: franklinkim.ufw, tags: ufw }
    - { role: zzet.rbenv, tags: rbenv }
    - { role: alekseyp.papertrail, tags: papertrail }

  tasks:
    - name: fix locales
      shell: >
        locale-gen en_US.UTF-8 && dpkg-reconfigure -fnoninteractive locales && update-locale LC_ALL="en_US.UTF-8" LANG="en_US.UTF-8" LANGUAGE="en_US" && touch ~/.locale_ok creates=~/.locale_ok

    - name: update apt cache
      apt: update_cache=yes

    - name: upgrade system
      apt: upgrade=safe

    - name: install required packages
      apt: pkg={{ item }}
      with_items:
        - build-essential
        - git-core
        - libxml2-dev
        - python-psycopg2
        - libpq-dev
        - imagemagick
        - zlib1g-dev
        - libssl-dev
        - libyaml-dev
        - libxml2-dev
        - bison
        - libreadline6
        - libreadline6-dev
      tags:
        - apt-packages

    - name: ensure bitbucket.org is a known host
      lineinfile:
        dest: /root/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}"
        regexp: "^bitbucket\\.org"

    - name: Source rbenv in ~/.zshrc
      lineinfile: dest=/home/nerdmaster/.zshrc line='export PATH="$HOME/.rbenv/bin:$PATH"' state=present insertafter=EOF create=yes
      tags:
        - rbenv-export

    - name: Add rbenv init to ~/.zshrc to enable shims and autocomplete
      lineinfile: dest=/home/nerdmaster/.zshrc line='eval "$(rbenv init -)"' state=present insertafter=EOF create=yes
      tags:
        - rbenv-init
