---

- name: 'Common configuration'
  hosts: 'all'
  gather_facts: True
  sudo: True

  # tasks:
  #   - include: provision.yml

# - name: ensure bitbucket.org is a known host
#   lineinfile:
#     dest: /root/.ssh/known_hosts
#     create: yes
#     state: present
#     line: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}"
#     regexp: "^bitbucket\\.org"

# - name: ensure postgresql hstore extension is created
#   sudo: yes
#   sudo_user: postgres
#   shell: "psql my_database -c 'CREATE EXTENSION hstore;'"
#   register: psql_result
#   failed_when: >
#     psql_result.rc != 0 and ("already exists" not in psql_result.stderr)
#   changed_when: "psql_result.rc == 0"
