---
htpasswd:
  - name: eunerd
    users:
      - { name: eunerd, password: nerdeu }
openssl_self_signed:
  - { name: 'staging.eunerd.com.br', country: 'BR', state: 'Paraná', city: 'Curitiba', organization: 'Encontre um Nerd', unit: '', email: 'admin@eunerd.com.br', days: 3650 }
nginx_http_params:
  - sendfile on
  - access_log /var/log/nginx/access-eunerd-staging.log
  - error_log /var/log/nginx/error-eunerd-staging.log
nginx_sites:
  eunerd:
    - listen *:80
    - listen *:443 ssl
    - server_name staging.eunerd.com.br www.staging.eunerd.com.br
    - root /home/deploy/apps/eunerd/current/public
    - ssl_protocols              SSLv3 TLSv1 TLSv1.1 TLSv1.2
    - ssl_ciphers                "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES"
    - ssl_prefer_server_ciphers  on
    - ssl_session_cache         shared:SSL:10m
    - ssl_session_timeout       10m
    - ssl_certificate /etc/ssl/certs/staging.eunerd.com.br.crt
    - ssl_certificate_key /etc/ssl/private/staging.eunerd.com.br.key
    - auth_basic "Staging - EUNERD"
    - auth_basic_user_file /etc/htpasswd/eunerd
    - location ~* (?:^|/)\. {
        deny all;
        access_log off;
        log_not_found off;
      }
    - location ~* (?:\.(?:bak|config|sql|fla|psd|ini|log|sh|inc|swp|dist)|~)$ {
        deny all;
        access_log off;
        log_not_found off;
      }
    - location / {
        try_files $uri $uri/ =404;
        if (-f $request_filename/index.html) {
          rewrite (.*) $1/index.html break;
        }

        if (-f $request_filename.html) {
          rewrite (.*) $1.html break;
        }

        if (!-f $request_filename) {
          proxy_pass http://eunerd;
          break;
        }
      }

nginx_configs:
  proxy:
    - proxy_set_header X-Real-IP  $remote_addr
    - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
    - proxy_set_header Host $http_host
    - proxy_redirect off
  upstream:
    - upstream eunerd { server unix:/tmp/unicorn.eunerd.socket fail_timeout=0; }
  gzip:
    - gzip on
    - gzip_disable msie6
    - gzip_http_version  1.0
    - gzip_comp_level    5
    - gzip_min_length    256
    - gzip_proxied       any
    - gzip_vary          on

rbenv:
  env: user
  version: v0.4.0
  ruby_version: 2.2.0
rbenv_users:
  - ubuntu
